nelmio_cors:
    defaults:
        allow_origin:  [ env(CORS_ALLOW_ORIGIN) ]
        allow_methods: [ 'POST', 'PUT', 'GET', 'DELETE', 'OPTIONS' ]
        allow_headers: [ 'content-type', 'authorization' ]
        max_age:       3600
    paths:
        '^/': ~